image: golang:1.13.5

pipelines:
  pull-requests:
    '**':
      - step:
          script:
            - apt-get update && apt-get install -y libltdl-dev zip
            - source bitbucket-pipelines-go.sh
            - cd ${IMPORT_PATH} && make print-go-env go-test
